name: Hugo CI

on:
  push:
    branches: [ master ]

jobs:
  hugo:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - uses: actions/cache@v2.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.12
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git submodule update --init --recursive
        npm install @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url
        hugo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
