name: Hugo CI

on:
  push:
    branches: [ master ]

jobs:
  hugo:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - uses: actions/cache@v2.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: buildandpush
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout gh-pages
        npm install @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url
        hugo &&\
        git add ./public/ &&\
        git commit -m "Hugo Builded $(git rev-parse --short HEAD)+$(git show -s --format=%ci $(git rev-parse HEAD)|tr ' ' '-')"
        git push origin HEAD:HEAD 
